title: Adventures With Linux & Friends
description: A site to talk about linux configurations and programming sometimes... maybe.

remote_theme: armory8854/blackarmor-jekyll-theme@v0.0.2
plugins:
  - jekyll-remote-theme

tag_page_layout: tag_page
tag_page_dir: tag
