title: Adventures With Linux & Friends
description: A site to talk about linux configurations and programming sometimes... maybe.

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
